import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 100 vh and 100vw */}
        <div className="w-screen h-screen bg-gradent-to-b from-blue-50 to-red-100">
          <Navbar />
          {children}
        </div>
        
      </body>
    </html>
  );
}
